on: [push]
jobs:
  ingestion_errors_slack:
    runs-on: ubuntu-latest
    name: dataflowerrors
    permissions:
      contents: 'read'
      id-token: 'write'


    steps:
    - uses: actions/checkout@v3
    

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'dataflow-errors-slack'
        description: 'Parsing Dataflow ingestion job errors and notify via Slack'
        runtime: 'python37'
        entry_point: 'processErrorMessage'
        source_dir: './code'
        project_id: 'international-gramercy'
        env_vars: PROJECT_ID=international-gramercy,DB_USER=liveramp,DB_NAME=ingestiondb ,DB_SOCKET_DIR=/cloudsql,INGESTION_SQL_INSTANCE_NAME= international-gramercy:europe-west1:international-ingestion-db-prod-cloudsql ,SLACK_WEBHOOK_URL=slack-webhook-url, INGESTION_DB_PSWD_URL=ingestion_db_pswd_url
        region: 'europe-west1'
        max_instances: 1
        event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
        event_trigger_resource: projects//topics/dataflow-error-logs-prod
